# Generated by Django 2.1.7 on 2019-03-25 10:17

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('compdata', '0001_initial'),
    ]

    operations = [
        migrations.AlterField(
            model_name='compdata',
            name='folder',
            field=models.TextField(),
        ),
        migrations.AlterField(
            model_name='compdata',
            name='fullname',
            field=models.TextField(),
        ),
    ]
